package country

type Info struct {
	Name                string
	ISO3166_1_numeric   int
	ISO3166_2           string
	ISO3166_3           string
	DefaultCurrency     string
	DefaultLanguage     string
	EuropeanUnionMember bool
}

var byISO1Numeric map[int]Info

var byISO2 map[string]Info

var byISO3 map[string]Info

func init() {
	byISO1Numeric = make(map[int]Info)

	byISO3 = make(map[string]Info)

	byISO2 = map[string]Info{

		"AF": {
			Name:                "Afghanistan",
			ISO3166_1_numeric:   4,
			ISO3166_2:           "AF",
			ISO3166_3:           "AFG",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ps",
			EuropeanUnionMember: false,
		},
		"AL": {
			Name:                "Albania",
			ISO3166_1_numeric:   8,
			ISO3166_2:           "AL",
			ISO3166_3:           "ALB",
			DefaultCurrency:     "ALL",
			DefaultLanguage:     "sq",
			EuropeanUnionMember: false,
		},
		"DZ": {
			Name:                "Algeria",
			ISO3166_1_numeric:   12,
			ISO3166_2:           "DZ",
			ISO3166_3:           "DZA",
			DefaultCurrency:     "DZD",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"AS": {
			Name:                "American Samoa",
			ISO3166_1_numeric:   16,
			ISO3166_2:           "AS",
			ISO3166_3:           "ASM",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"AD": {
			Name:                "Andorra",
			ISO3166_1_numeric:   20,
			ISO3166_2:           "AD",
			ISO3166_3:           "AND",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ca",
			EuropeanUnionMember: false,
		},
		"AO": {
			Name:                "Angola",
			ISO3166_1_numeric:   24,
			ISO3166_2:           "AO",
			ISO3166_3:           "AGO",
			DefaultCurrency:     "AOA",
			DefaultLanguage:     "kg",
			EuropeanUnionMember: false,
		},
		"AI": {
			Name:                "Anguilla",
			ISO3166_1_numeric:   660,
			ISO3166_2:           "AI",
			ISO3166_3:           "AIA",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"AQ": {
			Name:                "Antarctica",
			ISO3166_1_numeric:   10,
			ISO3166_2:           "AQ",
			ISO3166_3:           "ATA",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"AG": {
			Name:                "Antigua and Barbuda",
			ISO3166_1_numeric:   28,
			ISO3166_2:           "AG",
			ISO3166_3:           "ATG",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"AR": {
			Name:                "Argentina",
			ISO3166_1_numeric:   32,
			ISO3166_2:           "AR",
			ISO3166_3:           "ARG",
			DefaultCurrency:     "ARS",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"AM": {
			Name:                "Armenia",
			ISO3166_1_numeric:   51,
			ISO3166_2:           "AM",
			ISO3166_3:           "ARM",
			DefaultCurrency:     "AMD",
			DefaultLanguage:     "hy",
			EuropeanUnionMember: false,
		},
		"AW": {
			Name:                "Aruba",
			ISO3166_1_numeric:   533,
			ISO3166_2:           "AW",
			ISO3166_3:           "ABW",
			DefaultCurrency:     "AWG",
			DefaultLanguage:     "nl",
			EuropeanUnionMember: false,
		},
		"AU": {
			Name:                "Australia",
			ISO3166_1_numeric:   36,
			ISO3166_2:           "AU",
			ISO3166_3:           "AUS",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"AT": {
			Name:                "Austria",
			ISO3166_1_numeric:   40,
			ISO3166_2:           "AT",
			ISO3166_3:           "AUT",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "de",
			EuropeanUnionMember: true,
		},
		"AZ": {
			Name:                "Azerbaijan",
			ISO3166_1_numeric:   31,
			ISO3166_2:           "AZ",
			ISO3166_3:           "AZE",
			DefaultCurrency:     "AZN",
			DefaultLanguage:     "az",
			EuropeanUnionMember: false,
		},
		"BS": {
			Name:                "Bahamas",
			ISO3166_1_numeric:   44,
			ISO3166_2:           "BS",
			ISO3166_3:           "BHS",
			DefaultCurrency:     "BSD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"BH": {
			Name:                "Bahrain",
			ISO3166_1_numeric:   48,
			ISO3166_2:           "BH",
			ISO3166_3:           "BHR",
			DefaultCurrency:     "BHD",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"BD": {
			Name:                "Bangladesh",
			ISO3166_1_numeric:   50,
			ISO3166_2:           "BD",
			ISO3166_3:           "BGD",
			DefaultCurrency:     "BDT",
			DefaultLanguage:     "bn",
			EuropeanUnionMember: false,
		},
		"BB": {
			Name:                "Barbados",
			ISO3166_1_numeric:   52,
			ISO3166_2:           "BB",
			ISO3166_3:           "BRB",
			DefaultCurrency:     "BBD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"BY": {
			Name:                "Belarus",
			ISO3166_1_numeric:   112,
			ISO3166_2:           "BY",
			ISO3166_3:           "BLR",
			DefaultCurrency:     "BYN",
			DefaultLanguage:     "be",
			EuropeanUnionMember: false,
		},
		"BE": {
			Name:                "Belgium",
			ISO3166_1_numeric:   56,
			ISO3166_2:           "BE",
			ISO3166_3:           "BEL",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "nl",
			EuropeanUnionMember: true,
		},
		"BZ": {
			Name:                "Belize",
			ISO3166_1_numeric:   84,
			ISO3166_2:           "BZ",
			ISO3166_3:           "BLZ",
			DefaultCurrency:     "BZD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"BJ": {
			Name:                "Benin",
			ISO3166_1_numeric:   204,
			ISO3166_2:           "BJ",
			ISO3166_3:           "BEN",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"BM": {
			Name:                "Bermuda",
			ISO3166_1_numeric:   60,
			ISO3166_2:           "BM",
			ISO3166_3:           "BMU",
			DefaultCurrency:     "BMD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"BT": {
			Name:                "Bhutan",
			ISO3166_1_numeric:   64,
			ISO3166_2:           "BT",
			ISO3166_3:           "BTN",
			DefaultCurrency:     "INR",
			DefaultLanguage:     "dz",
			EuropeanUnionMember: false,
		},
		"BO": {
			Name:                "Bolivia",
			ISO3166_1_numeric:   68,
			ISO3166_2:           "BO",
			ISO3166_3:           "BOL",
			DefaultCurrency:     "BOB",
			DefaultLanguage:     "ay",
			EuropeanUnionMember: false,
		},
		"BQ": {
			Name:                "Bonaire, Sint Eustatius and Saba",
			ISO3166_1_numeric:   535,
			ISO3166_2:           "BQ",
			ISO3166_3:           "BES",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"BA": {
			Name:                "Bosnia and Herzegovina",
			ISO3166_1_numeric:   70,
			ISO3166_2:           "BA",
			ISO3166_3:           "BIH",
			DefaultCurrency:     "BAM",
			DefaultLanguage:     "bs",
			EuropeanUnionMember: false,
		},
		"BW": {
			Name:                "Botswana",
			ISO3166_1_numeric:   72,
			ISO3166_2:           "BW",
			ISO3166_3:           "BWA",
			DefaultCurrency:     "BWP",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"BV": {
			Name:                "Bouvet Island",
			ISO3166_1_numeric:   74,
			ISO3166_2:           "BV",
			ISO3166_3:           "BVT",
			DefaultCurrency:     "NOK",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"BR": {
			Name:                "Brazil",
			ISO3166_1_numeric:   76,
			ISO3166_2:           "BR",
			ISO3166_3:           "BRA",
			DefaultCurrency:     "BRL",
			DefaultLanguage:     "pt",
			EuropeanUnionMember: false,
		},
		"IO": {
			Name:                "British Indian Ocean Territory",
			ISO3166_1_numeric:   86,
			ISO3166_2:           "IO",
			ISO3166_3:           "IOT",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"VG": {
			Name:                "British Virgin Islands",
			ISO3166_1_numeric:   92,
			ISO3166_2:           "VG",
			ISO3166_3:           "VGB",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"BN": {
			Name:                "Brunei Darussalam",
			ISO3166_1_numeric:   96,
			ISO3166_2:           "BN",
			ISO3166_3:           "BRN",
			DefaultCurrency:     "BND",
			DefaultLanguage:     "ms",
			EuropeanUnionMember: false,
		},
		"BG": {
			Name:                "Bulgaria",
			ISO3166_1_numeric:   100,
			ISO3166_2:           "BG",
			ISO3166_3:           "BGR",
			DefaultCurrency:     "BGN",
			DefaultLanguage:     "bg",
			EuropeanUnionMember: true,
		},
		"BF": {
			Name:                "Burkina Faso",
			ISO3166_1_numeric:   854,
			ISO3166_2:           "BF",
			ISO3166_3:           "BFA",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"BI": {
			Name:                "Burundi",
			ISO3166_1_numeric:   108,
			ISO3166_2:           "BI",
			ISO3166_3:           "BDI",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"CV": {
			Name:                "Cabo Verde",
			ISO3166_1_numeric:   132,
			ISO3166_2:           "CV",
			ISO3166_3:           "CPV",
			DefaultCurrency:     "CVE",
			DefaultLanguage:     "pt",
			EuropeanUnionMember: false,
		},
		"KH": {
			Name:                "Cambodia",
			ISO3166_1_numeric:   116,
			ISO3166_2:           "KH",
			ISO3166_3:           "KHM",
			DefaultCurrency:     "KHR",
			DefaultLanguage:     "km",
			EuropeanUnionMember: false,
		},
		"CM": {
			Name:                "Cameroon",
			ISO3166_1_numeric:   120,
			ISO3166_2:           "CM",
			ISO3166_3:           "CMR",
			DefaultCurrency:     "XAF",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"CA": {
			Name:                "Canada",
			ISO3166_1_numeric:   124,
			ISO3166_2:           "CA",
			ISO3166_3:           "CAN",
			DefaultCurrency:     "CAD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"KY": {
			Name:                "Cayman Islands",
			ISO3166_1_numeric:   136,
			ISO3166_2:           "KY",
			ISO3166_3:           "CYM",
			DefaultCurrency:     "KYD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"CF": {
			Name:                "Central African Republic",
			ISO3166_1_numeric:   140,
			ISO3166_2:           "CF",
			ISO3166_3:           "CAF",
			DefaultCurrency:     "XAF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"TD": {
			Name:                "Chad",
			ISO3166_1_numeric:   148,
			ISO3166_2:           "TD",
			ISO3166_3:           "TCD",
			DefaultCurrency:     "XAF",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"CL": {
			Name:                "Chile",
			ISO3166_1_numeric:   152,
			ISO3166_2:           "CL",
			ISO3166_3:           "CHL",
			DefaultCurrency:     "CLP",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"CN": {
			Name:                "China",
			ISO3166_1_numeric:   156,
			ISO3166_2:           "CN",
			ISO3166_3:           "CHN",
			DefaultCurrency:     "CNY",
			DefaultLanguage:     "zh",
			EuropeanUnionMember: false,
		},
		"CX": {
			Name:                "Christmas Island",
			ISO3166_1_numeric:   162,
			ISO3166_2:           "CX",
			ISO3166_3:           "CXR",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"CC": {
			Name:                "Cocos (Keeling) Islands",
			ISO3166_1_numeric:   166,
			ISO3166_2:           "CC",
			ISO3166_3:           "CCK",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"CO": {
			Name:                "Colombia",
			ISO3166_1_numeric:   170,
			ISO3166_2:           "CO",
			ISO3166_3:           "COL",
			DefaultCurrency:     "COP",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"KM": {
			Name:                "Comoros",
			ISO3166_1_numeric:   174,
			ISO3166_2:           "KM",
			ISO3166_3:           "COM",
			DefaultCurrency:     "KMF",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"CG": {
			Name:                "Congo",
			ISO3166_1_numeric:   178,
			ISO3166_2:           "CG",
			ISO3166_3:           "COG",
			DefaultCurrency:     "XAF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"CK": {
			Name:                "Cook Islands",
			ISO3166_1_numeric:   184,
			ISO3166_2:           "CK",
			ISO3166_3:           "COK",
			DefaultCurrency:     "NZD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"CR": {
			Name:                "Costa Rica",
			ISO3166_1_numeric:   188,
			ISO3166_2:           "CR",
			ISO3166_3:           "CRI",
			DefaultCurrency:     "CRC",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"HR": {
			Name:                "Croatia",
			ISO3166_1_numeric:   191,
			ISO3166_2:           "HR",
			ISO3166_3:           "HRV",
			DefaultCurrency:     "HRK",
			DefaultLanguage:     "hr",
			EuropeanUnionMember: true,
		},
		"CU": {
			Name:                "Cuba",
			ISO3166_1_numeric:   192,
			ISO3166_2:           "CU",
			ISO3166_3:           "CUB",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"CW": {
			Name:                "Curaçao",
			ISO3166_1_numeric:   531,
			ISO3166_2:           "CW",
			ISO3166_3:           "CUW",
			DefaultCurrency:     "ANG",
			DefaultLanguage:     "nl",
			EuropeanUnionMember: false,
		},
		"CY": {
			Name:                "Cyprus",
			ISO3166_1_numeric:   196,
			ISO3166_2:           "CY",
			ISO3166_3:           "CYP",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "el",
			EuropeanUnionMember: true,
		},
		"CZ": {
			Name:                "Czechia",
			ISO3166_1_numeric:   203,
			ISO3166_2:           "CZ",
			ISO3166_3:           "CZE",
			DefaultCurrency:     "CZK",
			DefaultLanguage:     "cs",
			EuropeanUnionMember: true,
		},
		"CI": {
			Name:                "Côte d'Ivoire",
			ISO3166_1_numeric:   384,
			ISO3166_2:           "CI",
			ISO3166_3:           "CIV",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"KP": {
			Name:                "Democratic People's Republic of Korea",
			ISO3166_1_numeric:   408,
			ISO3166_2:           "KP",
			ISO3166_3:           "PRK",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ko",
			EuropeanUnionMember: false,
		},
		"CD": {
			Name:                "Democratic Republic of the Congo",
			ISO3166_1_numeric:   180,
			ISO3166_2:           "CD",
			ISO3166_3:           "COD",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"DK": {
			Name:                "Denmark",
			ISO3166_1_numeric:   208,
			ISO3166_2:           "DK",
			ISO3166_3:           "DNK",
			DefaultCurrency:     "DKK",
			DefaultLanguage:     "da",
			EuropeanUnionMember: true,
		},
		"DJ": {
			Name:                "Djibouti",
			ISO3166_1_numeric:   262,
			ISO3166_2:           "DJ",
			ISO3166_3:           "DJI",
			DefaultCurrency:     "DJF",
			DefaultLanguage:     "aa",
			EuropeanUnionMember: false,
		},
		"DM": {
			Name:                "Dominica",
			ISO3166_1_numeric:   212,
			ISO3166_2:           "DM",
			ISO3166_3:           "DMA",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"DO": {
			Name:                "Dominican Republic",
			ISO3166_1_numeric:   214,
			ISO3166_2:           "DO",
			ISO3166_3:           "DOM",
			DefaultCurrency:     "DOP",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"EC": {
			Name:                "Ecuador",
			ISO3166_1_numeric:   218,
			ISO3166_2:           "EC",
			ISO3166_3:           "ECU",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"EG": {
			Name:                "Egypt",
			ISO3166_1_numeric:   818,
			ISO3166_2:           "EG",
			ISO3166_3:           "EGY",
			DefaultCurrency:     "EGP",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"SV": {
			Name:                "El Salvador",
			ISO3166_1_numeric:   222,
			ISO3166_2:           "SV",
			ISO3166_3:           "SLV",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"GQ": {
			Name:                "Equatorial Guinea",
			ISO3166_1_numeric:   226,
			ISO3166_2:           "GQ",
			ISO3166_3:           "GNQ",
			DefaultCurrency:     "XAF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"ER": {
			Name:                "Eritrea",
			ISO3166_1_numeric:   232,
			ISO3166_2:           "ER",
			ISO3166_3:           "ERI",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"EE": {
			Name:                "Estonia",
			ISO3166_1_numeric:   233,
			ISO3166_2:           "EE",
			ISO3166_3:           "EST",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "et",
			EuropeanUnionMember: true,
		},
		"SZ": {
			Name:                "Eswatini",
			ISO3166_1_numeric:   748,
			ISO3166_2:           "SZ",
			ISO3166_3:           "SWZ",
			DefaultCurrency:     "SZL",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"ET": {
			Name:                "Ethiopia",
			ISO3166_1_numeric:   231,
			ISO3166_2:           "ET",
			ISO3166_3:           "ETH",
			DefaultCurrency:     "ETB",
			DefaultLanguage:     "am",
			EuropeanUnionMember: false,
		},
		"FK": {
			Name:                "Falkland Islands",
			ISO3166_1_numeric:   238,
			ISO3166_2:           "FK",
			ISO3166_3:           "FLK",
			DefaultCurrency:     "FKP",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"FO": {
			Name:                "Faroe Islands",
			ISO3166_1_numeric:   234,
			ISO3166_2:           "FO",
			ISO3166_3:           "FRO",
			DefaultCurrency:     "DKK",
			DefaultLanguage:     "da",
			EuropeanUnionMember: false,
		},
		"FJ": {
			Name:                "Fiji",
			ISO3166_1_numeric:   242,
			ISO3166_2:           "FJ",
			ISO3166_3:           "FJI",
			DefaultCurrency:     "FJD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"FI": {
			Name:                "Finland",
			ISO3166_1_numeric:   246,
			ISO3166_2:           "FI",
			ISO3166_3:           "FIN",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fi",
			EuropeanUnionMember: true,
		},
		"FR": {
			Name:                "France",
			ISO3166_1_numeric:   250,
			ISO3166_2:           "FR",
			ISO3166_3:           "FRA",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: true,
		},
		"GF": {
			Name:                "French Guiana",
			ISO3166_1_numeric:   254,
			ISO3166_2:           "GF",
			ISO3166_3:           "GUF",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"PF": {
			Name:                "French Polynesia",
			ISO3166_1_numeric:   258,
			ISO3166_2:           "PF",
			ISO3166_3:           "PYF",
			DefaultCurrency:     "XPF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"TF": {
			Name:                "French Southern Territories",
			ISO3166_1_numeric:   260,
			ISO3166_2:           "TF",
			ISO3166_3:           "ATF",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"GA": {
			Name:                "Gabon",
			ISO3166_1_numeric:   266,
			ISO3166_2:           "GA",
			ISO3166_3:           "GAB",
			DefaultCurrency:     "XAF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"GM": {
			Name:                "Gambia",
			ISO3166_1_numeric:   270,
			ISO3166_2:           "GM",
			ISO3166_3:           "GMB",
			DefaultCurrency:     "GMD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"GE": {
			Name:                "Georgia",
			ISO3166_1_numeric:   268,
			ISO3166_2:           "GE",
			ISO3166_3:           "GEO",
			DefaultCurrency:     "GEL",
			DefaultLanguage:     "ka",
			EuropeanUnionMember: false,
		},
		"DE": {
			Name:                "Germany",
			ISO3166_1_numeric:   276,
			ISO3166_2:           "DE",
			ISO3166_3:           "DEU",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "de",
			EuropeanUnionMember: true,
		},
		"GH": {
			Name:                "Ghana",
			ISO3166_1_numeric:   288,
			ISO3166_2:           "GH",
			ISO3166_3:           "GHA",
			DefaultCurrency:     "GHS",
			DefaultLanguage:     "ak",
			EuropeanUnionMember: false,
		},
		"GI": {
			Name:                "Gibraltar",
			ISO3166_1_numeric:   292,
			ISO3166_2:           "GI",
			ISO3166_3:           "GIB",
			DefaultCurrency:     "GIP",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"GR": {
			Name:                "Greece",
			ISO3166_1_numeric:   300,
			ISO3166_2:           "GR",
			ISO3166_3:           "GRC",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "el",
			EuropeanUnionMember: true,
		},
		"GL": {
			Name:                "Greenland",
			ISO3166_1_numeric:   304,
			ISO3166_2:           "GL",
			ISO3166_3:           "GRL",
			DefaultCurrency:     "DKK",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"GD": {
			Name:                "Grenada",
			ISO3166_1_numeric:   308,
			ISO3166_2:           "GD",
			ISO3166_3:           "GRD",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"GP": {
			Name:                "Guadeloupe",
			ISO3166_1_numeric:   312,
			ISO3166_2:           "GP",
			ISO3166_3:           "GLP",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"GU": {
			Name:                "Guam",
			ISO3166_1_numeric:   316,
			ISO3166_2:           "GU",
			ISO3166_3:           "GUM",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"GT": {
			Name:                "Guatemala",
			ISO3166_1_numeric:   320,
			ISO3166_2:           "GT",
			ISO3166_3:           "GTM",
			DefaultCurrency:     "GTQ",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"GG": {
			Name:                "Guernsey",
			ISO3166_1_numeric:   831,
			ISO3166_2:           "GG",
			ISO3166_3:           "GGY",
			DefaultCurrency:     "GBP",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"GN": {
			Name:                "Guinea",
			ISO3166_1_numeric:   324,
			ISO3166_2:           "GN",
			ISO3166_3:           "GIN",
			DefaultCurrency:     "GNF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"GW": {
			Name:                "Guinea-Bissau",
			ISO3166_1_numeric:   624,
			ISO3166_2:           "GW",
			ISO3166_3:           "GNB",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "pt",
			EuropeanUnionMember: false,
		},
		"GY": {
			Name:                "Guyana",
			ISO3166_1_numeric:   328,
			ISO3166_2:           "GY",
			ISO3166_3:           "GUY",
			DefaultCurrency:     "GYD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"HT": {
			Name:                "Haiti",
			ISO3166_1_numeric:   332,
			ISO3166_2:           "HT",
			ISO3166_3:           "HTI",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"HM": {
			Name:                "Heard Island and McDonald Islands",
			ISO3166_1_numeric:   334,
			ISO3166_2:           "HM",
			ISO3166_3:           "HMD",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"VA": {
			Name:                "Holy See",
			ISO3166_1_numeric:   336,
			ISO3166_2:           "VA",
			ISO3166_3:           "VAT",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "it",
			EuropeanUnionMember: false,
		},
		"HN": {
			Name:                "Honduras",
			ISO3166_1_numeric:   340,
			ISO3166_2:           "HN",
			ISO3166_3:           "HND",
			DefaultCurrency:     "HNL",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"HK": {
			Name:                "Hong Kong",
			ISO3166_1_numeric:   344,
			ISO3166_2:           "HK",
			ISO3166_3:           "HKG",
			DefaultCurrency:     "HKD",
			DefaultLanguage:     "zh",
			EuropeanUnionMember: false,
		},
		"HU": {
			Name:                "Hungary",
			ISO3166_1_numeric:   348,
			ISO3166_2:           "HU",
			ISO3166_3:           "HUN",
			DefaultCurrency:     "HUF",
			DefaultLanguage:     "hu",
			EuropeanUnionMember: true,
		},
		"IS": {
			Name:                "Iceland",
			ISO3166_1_numeric:   352,
			ISO3166_2:           "IS",
			ISO3166_3:           "ISL",
			DefaultCurrency:     "ISK",
			DefaultLanguage:     "is",
			EuropeanUnionMember: false,
		},
		"IN": {
			Name:                "India",
			ISO3166_1_numeric:   356,
			ISO3166_2:           "IN",
			ISO3166_3:           "IND",
			DefaultCurrency:     "INR",
			DefaultLanguage:     "bn",
			EuropeanUnionMember: false,
		},
		"ID": {
			Name:                "Indonesia",
			ISO3166_1_numeric:   360,
			ISO3166_2:           "ID",
			ISO3166_3:           "IDN",
			DefaultCurrency:     "IDR",
			DefaultLanguage:     "id",
			EuropeanUnionMember: false,
		},
		"IR": {
			Name:                "Iran (Islamic Republic of)",
			ISO3166_1_numeric:   364,
			ISO3166_2:           "IR",
			ISO3166_3:           "IRN",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fa",
			EuropeanUnionMember: false,
		},
		"IQ": {
			Name:                "Iraq",
			ISO3166_1_numeric:   368,
			ISO3166_2:           "IQ",
			ISO3166_3:           "IRQ",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"IE": {
			Name:                "Ireland",
			ISO3166_1_numeric:   372,
			ISO3166_2:           "IE",
			ISO3166_3:           "IRL",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: true,
		},
		"IM": {
			Name:                "Isle of Man",
			ISO3166_1_numeric:   833,
			ISO3166_2:           "IM",
			ISO3166_3:           "IMN",
			DefaultCurrency:     "GBP",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"IL": {
			Name:                "Israel",
			ISO3166_1_numeric:   376,
			ISO3166_2:           "IL",
			ISO3166_3:           "ISR",
			DefaultCurrency:     "ILS",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"IT": {
			Name:                "Italy",
			ISO3166_1_numeric:   380,
			ISO3166_2:           "IT",
			ISO3166_3:           "ITA",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "it",
			EuropeanUnionMember: true,
		},
		"JM": {
			Name:                "Jamaica",
			ISO3166_1_numeric:   388,
			ISO3166_2:           "JM",
			ISO3166_3:           "JAM",
			DefaultCurrency:     "JMD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"JP": {
			Name:                "Japan",
			ISO3166_1_numeric:   392,
			ISO3166_2:           "JP",
			ISO3166_3:           "JPN",
			DefaultCurrency:     "JPY",
			DefaultLanguage:     "ja",
			EuropeanUnionMember: false,
		},
		"JE": {
			Name:                "Jersey",
			ISO3166_1_numeric:   832,
			ISO3166_2:           "JE",
			ISO3166_3:           "JEY",
			DefaultCurrency:     "GBP",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"JO": {
			Name:                "Jordan",
			ISO3166_1_numeric:   400,
			ISO3166_2:           "JO",
			ISO3166_3:           "JOR",
			DefaultCurrency:     "JOD",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"KZ": {
			Name:                "Kazakhstan",
			ISO3166_1_numeric:   398,
			ISO3166_2:           "KZ",
			ISO3166_3:           "KAZ",
			DefaultCurrency:     "KZT",
			DefaultLanguage:     "kk",
			EuropeanUnionMember: false,
		},
		"KE": {
			Name:                "Kenya",
			ISO3166_1_numeric:   404,
			ISO3166_2:           "KE",
			ISO3166_3:           "KEN",
			DefaultCurrency:     "KES",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"KI": {
			Name:                "Kiribati",
			ISO3166_1_numeric:   296,
			ISO3166_2:           "KI",
			ISO3166_3:           "KIR",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"KW": {
			Name:                "Kuwait",
			ISO3166_1_numeric:   414,
			ISO3166_2:           "KW",
			ISO3166_3:           "KWT",
			DefaultCurrency:     "KWD",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"KG": {
			Name:                "Kyrgyzstan",
			ISO3166_1_numeric:   417,
			ISO3166_2:           "KG",
			ISO3166_3:           "KGZ",
			DefaultCurrency:     "KGS",
			DefaultLanguage:     "ky",
			EuropeanUnionMember: false,
		},
		"LA": {
			Name:                "Lao People's Democratic Republic",
			ISO3166_1_numeric:   418,
			ISO3166_2:           "LA",
			ISO3166_3:           "LAO",
			DefaultCurrency:     "LAK",
			DefaultLanguage:     "lo",
			EuropeanUnionMember: false,
		},
		"LV": {
			Name:                "Latvia",
			ISO3166_1_numeric:   428,
			ISO3166_2:           "LV",
			ISO3166_3:           "LVA",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "lv",
			EuropeanUnionMember: true,
		},
		"LB": {
			Name:                "Lebanon",
			ISO3166_1_numeric:   422,
			ISO3166_2:           "LB",
			ISO3166_3:           "LBN",
			DefaultCurrency:     "LBP",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"LS": {
			Name:                "Lesotho",
			ISO3166_1_numeric:   426,
			ISO3166_2:           "LS",
			ISO3166_3:           "LSO",
			DefaultCurrency:     "ZAR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"LR": {
			Name:                "Liberia",
			ISO3166_1_numeric:   430,
			ISO3166_2:           "LR",
			ISO3166_3:           "LBR",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"LY": {
			Name:                "Libya",
			ISO3166_1_numeric:   434,
			ISO3166_2:           "LY",
			ISO3166_3:           "LBY",
			DefaultCurrency:     "LYD",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"LI": {
			Name:                "Liechtenstein",
			ISO3166_1_numeric:   438,
			ISO3166_2:           "LI",
			ISO3166_3:           "LIE",
			DefaultCurrency:     "CHF",
			DefaultLanguage:     "de",
			EuropeanUnionMember: false,
		},
		"LT": {
			Name:                "Lithuania",
			ISO3166_1_numeric:   440,
			ISO3166_2:           "LT",
			ISO3166_3:           "LTU",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "lt",
			EuropeanUnionMember: true,
		},
		"LU": {
			Name:                "Luxembourg",
			ISO3166_1_numeric:   442,
			ISO3166_2:           "LU",
			ISO3166_3:           "LUX",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: true,
		},
		"MO": {
			Name:                "Macau",
			ISO3166_1_numeric:   446,
			ISO3166_2:           "MO",
			ISO3166_3:           "MAC",
			DefaultCurrency:     "MOP",
			DefaultLanguage:     "zh",
			EuropeanUnionMember: false,
		},
		"MG": {
			Name:                "Madagascar",
			ISO3166_1_numeric:   450,
			ISO3166_2:           "MG",
			ISO3166_3:           "MDG",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"MW": {
			Name:                "Malawi",
			ISO3166_1_numeric:   454,
			ISO3166_2:           "MW",
			ISO3166_3:           "MWI",
			DefaultCurrency:     "MWK",
			DefaultLanguage:     "ny",
			EuropeanUnionMember: false,
		},
		"MY": {
			Name:                "Malaysia",
			ISO3166_1_numeric:   458,
			ISO3166_2:           "MY",
			ISO3166_3:           "MYS",
			DefaultCurrency:     "MYR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"MV": {
			Name:                "Maldives",
			ISO3166_1_numeric:   462,
			ISO3166_2:           "MV",
			ISO3166_3:           "MDV",
			DefaultCurrency:     "MVR",
			DefaultLanguage:     "dv",
			EuropeanUnionMember: false,
		},
		"ML": {
			Name:                "Mali",
			ISO3166_1_numeric:   466,
			ISO3166_2:           "ML",
			ISO3166_3:           "MLI",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "bm",
			EuropeanUnionMember: false,
		},
		"MT": {
			Name:                "Malta",
			ISO3166_1_numeric:   470,
			ISO3166_2:           "MT",
			ISO3166_3:           "MLT",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: true,
		},
		"MH": {
			Name:                "Marshall Islands",
			ISO3166_1_numeric:   584,
			ISO3166_2:           "MH",
			ISO3166_3:           "MHL",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"MQ": {
			Name:                "Martinique",
			ISO3166_1_numeric:   474,
			ISO3166_2:           "MQ",
			ISO3166_3:           "MTQ",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"MR": {
			Name:                "Mauritania",
			ISO3166_1_numeric:   478,
			ISO3166_2:           "MR",
			ISO3166_3:           "MRT",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"MU": {
			Name:                "Mauritius",
			ISO3166_1_numeric:   480,
			ISO3166_2:           "MU",
			ISO3166_3:           "MUS",
			DefaultCurrency:     "MUR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"YT": {
			Name:                "Mayotte",
			ISO3166_1_numeric:   175,
			ISO3166_2:           "YT",
			ISO3166_3:           "MYT",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"MX": {
			Name:                "Mexico",
			ISO3166_1_numeric:   484,
			ISO3166_2:           "MX",
			ISO3166_3:           "MEX",
			DefaultCurrency:     "MXN",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"FM": {
			Name:                "Micronesia",
			ISO3166_1_numeric:   583,
			ISO3166_2:           "FM",
			ISO3166_3:           "FSM",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"MC": {
			Name:                "Monaco",
			ISO3166_1_numeric:   492,
			ISO3166_2:           "MC",
			ISO3166_3:           "MCO",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"MN": {
			Name:                "Mongolia",
			ISO3166_1_numeric:   496,
			ISO3166_2:           "MN",
			ISO3166_3:           "MNG",
			DefaultCurrency:     "MNT",
			DefaultLanguage:     "mn",
			EuropeanUnionMember: false,
		},
		"ME": {
			Name:                "Montenegro",
			ISO3166_1_numeric:   499,
			ISO3166_2:           "ME",
			ISO3166_3:           "MNE",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"MS": {
			Name:                "Montserrat",
			ISO3166_1_numeric:   500,
			ISO3166_2:           "MS",
			ISO3166_3:           "MSR",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"MA": {
			Name:                "Morocco",
			ISO3166_1_numeric:   504,
			ISO3166_2:           "MA",
			ISO3166_3:           "MAR",
			DefaultCurrency:     "MAD",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"MZ": {
			Name:                "Mozambique",
			ISO3166_1_numeric:   508,
			ISO3166_2:           "MZ",
			ISO3166_3:           "MOZ",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "pt",
			EuropeanUnionMember: false,
		},
		"MM": {
			Name:                "Myanmar",
			ISO3166_1_numeric:   104,
			ISO3166_2:           "MM",
			ISO3166_3:           "MMR",
			DefaultCurrency:     "MMK",
			DefaultLanguage:     "my",
			EuropeanUnionMember: false,
		},
		"NA": {
			Name:                "Namibia",
			ISO3166_1_numeric:   516,
			ISO3166_2:           "NA",
			ISO3166_3:           "NAM",
			DefaultCurrency:     "NAD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"NR": {
			Name:                "Nauru",
			ISO3166_1_numeric:   520,
			ISO3166_2:           "NR",
			ISO3166_3:           "NRU",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"NP": {
			Name:                "Nepal",
			ISO3166_1_numeric:   524,
			ISO3166_2:           "NP",
			ISO3166_3:           "NPL",
			DefaultCurrency:     "NPR",
			DefaultLanguage:     "ne",
			EuropeanUnionMember: false,
		},
		"NL": {
			Name:                "Netherlands",
			ISO3166_1_numeric:   528,
			ISO3166_2:           "NL",
			ISO3166_3:           "NLD",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "nl",
			EuropeanUnionMember: true,
		},
		"NC": {
			Name:                "New Caledonia",
			ISO3166_1_numeric:   540,
			ISO3166_2:           "NC",
			ISO3166_3:           "NCL",
			DefaultCurrency:     "XPF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"NZ": {
			Name:                "New Zealand",
			ISO3166_1_numeric:   554,
			ISO3166_2:           "NZ",
			ISO3166_3:           "NZL",
			DefaultCurrency:     "NZD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"NI": {
			Name:                "Nicaragua",
			ISO3166_1_numeric:   558,
			ISO3166_2:           "NI",
			ISO3166_3:           "NIC",
			DefaultCurrency:     "NIO",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"NE": {
			Name:                "Niger",
			ISO3166_1_numeric:   562,
			ISO3166_2:           "NE",
			ISO3166_3:           "NER",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"NG": {
			Name:                "Nigeria",
			ISO3166_1_numeric:   566,
			ISO3166_2:           "NG",
			ISO3166_3:           "NGA",
			DefaultCurrency:     "NGN",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"NU": {
			Name:                "Niue",
			ISO3166_1_numeric:   570,
			ISO3166_2:           "NU",
			ISO3166_3:           "NIU",
			DefaultCurrency:     "NZD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"NF": {
			Name:                "Norfolk Island",
			ISO3166_1_numeric:   574,
			ISO3166_2:           "NF",
			ISO3166_3:           "NFK",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"MP": {
			Name:                "Northern Mariana Islands",
			ISO3166_1_numeric:   580,
			ISO3166_2:           "MP",
			ISO3166_3:           "MNP",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"NO": {
			Name:                "Norway",
			ISO3166_1_numeric:   578,
			ISO3166_2:           "NO",
			ISO3166_3:           "NOR",
			DefaultCurrency:     "NOK",
			DefaultLanguage:     "no",
			EuropeanUnionMember: false,
		},
		"OM": {
			Name:                "Oman",
			ISO3166_1_numeric:   512,
			ISO3166_2:           "OM",
			ISO3166_3:           "OMN",
			DefaultCurrency:     "OMR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"PK": {
			Name:                "Pakistan",
			ISO3166_1_numeric:   586,
			ISO3166_2:           "PK",
			ISO3166_3:           "PAK",
			DefaultCurrency:     "PKR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"PW": {
			Name:                "Palau",
			ISO3166_1_numeric:   585,
			ISO3166_2:           "PW",
			ISO3166_3:           "PLW",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"PA": {
			Name:                "Panama",
			ISO3166_1_numeric:   591,
			ISO3166_2:           "PA",
			ISO3166_3:           "PAN",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"PG": {
			Name:                "Papua New Guinea",
			ISO3166_1_numeric:   598,
			ISO3166_2:           "PG",
			ISO3166_3:           "PNG",
			DefaultCurrency:     "PGK",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"PY": {
			Name:                "Paraguay",
			ISO3166_1_numeric:   600,
			ISO3166_2:           "PY",
			ISO3166_3:           "PRY",
			DefaultCurrency:     "PYG",
			DefaultLanguage:     "gn",
			EuropeanUnionMember: false,
		},
		"PE": {
			Name:                "Peru",
			ISO3166_1_numeric:   604,
			ISO3166_2:           "PE",
			ISO3166_3:           "PER",
			DefaultCurrency:     "PEN",
			DefaultLanguage:     "ay",
			EuropeanUnionMember: false,
		},
		"PH": {
			Name:                "Philippines",
			ISO3166_1_numeric:   608,
			ISO3166_2:           "PH",
			ISO3166_3:           "PHL",
			DefaultCurrency:     "PHP",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"PN": {
			Name:                "Pitcairn",
			ISO3166_1_numeric:   612,
			ISO3166_2:           "PN",
			ISO3166_3:           "PCN",
			DefaultCurrency:     "NZD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"PL": {
			Name:                "Poland",
			ISO3166_1_numeric:   616,
			ISO3166_2:           "PL",
			ISO3166_3:           "POL",
			DefaultCurrency:     "PLN",
			DefaultLanguage:     "pl",
			EuropeanUnionMember: true,
		},
		"PT": {
			Name:                "Portugal",
			ISO3166_1_numeric:   620,
			ISO3166_2:           "PT",
			ISO3166_3:           "PRT",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "pt",
			EuropeanUnionMember: true,
		},
		"PR": {
			Name:                "Puerto Rico",
			ISO3166_1_numeric:   630,
			ISO3166_2:           "PR",
			ISO3166_3:           "PRI",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"QA": {
			Name:                "Qatar",
			ISO3166_1_numeric:   634,
			ISO3166_2:           "QA",
			ISO3166_3:           "QAT",
			DefaultCurrency:     "QAR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"KR": {
			Name:                "Republic of Korea",
			ISO3166_1_numeric:   410,
			ISO3166_2:           "KR",
			ISO3166_3:           "KOR",
			DefaultCurrency:     "KRW",
			DefaultLanguage:     "ko",
			EuropeanUnionMember: false,
		},
		"MD": {
			Name:                "Republic of Moldova",
			ISO3166_1_numeric:   498,
			ISO3166_2:           "MD",
			ISO3166_3:           "MDA",
			DefaultCurrency:     "MDL",
			DefaultLanguage:     "ro",
			EuropeanUnionMember: false,
		},
		"RO": {
			Name:                "Romania",
			ISO3166_1_numeric:   642,
			ISO3166_2:           "RO",
			ISO3166_3:           "ROU",
			DefaultCurrency:     "RON",
			DefaultLanguage:     "ro",
			EuropeanUnionMember: true,
		},
		"RU": {
			Name:                "Russian Federation",
			ISO3166_1_numeric:   643,
			ISO3166_2:           "RU",
			ISO3166_3:           "RUS",
			DefaultCurrency:     "RUB",
			DefaultLanguage:     "ru",
			EuropeanUnionMember: false,
		},
		"RW": {
			Name:                "Rwanda",
			ISO3166_1_numeric:   646,
			ISO3166_2:           "RW",
			ISO3166_3:           "RWA",
			DefaultCurrency:     "RWF",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"RE": {
			Name:                "Réunion",
			ISO3166_1_numeric:   638,
			ISO3166_2:           "RE",
			ISO3166_3:           "REU",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"BL": {
			Name:                "Saint Barthélemy",
			ISO3166_1_numeric:   652,
			ISO3166_2:           "BL",
			ISO3166_3:           "BLM",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"SH": {
			Name:                "Saint Helena",
			ISO3166_1_numeric:   654,
			ISO3166_2:           "SH",
			ISO3166_3:           "SHN",
			DefaultCurrency:     "SHP",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"KN": {
			Name:                "Saint Kitts and Nevis",
			ISO3166_1_numeric:   659,
			ISO3166_2:           "KN",
			ISO3166_3:           "KNA",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"LC": {
			Name:                "Saint Lucia",
			ISO3166_1_numeric:   662,
			ISO3166_2:           "LC",
			ISO3166_3:           "LCA",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"MF": {
			Name:                "Saint Martin",
			ISO3166_1_numeric:   663,
			ISO3166_2:           "MF",
			ISO3166_3:           "MAF",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"PM": {
			Name:                "Saint Pierre and Miquelon",
			ISO3166_1_numeric:   666,
			ISO3166_2:           "PM",
			ISO3166_3:           "SPM",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"VC": {
			Name:                "Saint Vincent and the Grenadines",
			ISO3166_1_numeric:   670,
			ISO3166_2:           "VC",
			ISO3166_3:           "VCT",
			DefaultCurrency:     "XCD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"WS": {
			Name:                "Samoa",
			ISO3166_1_numeric:   882,
			ISO3166_2:           "WS",
			ISO3166_3:           "WSM",
			DefaultCurrency:     "WST",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"SM": {
			Name:                "San Marino",
			ISO3166_1_numeric:   674,
			ISO3166_2:           "SM",
			ISO3166_3:           "SMR",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "it",
			EuropeanUnionMember: false,
		},
		"ST": {
			Name:                "Sao Tome and Principe",
			ISO3166_1_numeric:   678,
			ISO3166_2:           "ST",
			ISO3166_3:           "STP",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "pt",
			EuropeanUnionMember: false,
		},
		"SA": {
			Name:                "Saudi Arabia",
			ISO3166_1_numeric:   682,
			ISO3166_2:           "SA",
			ISO3166_3:           "SAU",
			DefaultCurrency:     "SAR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"SN": {
			Name:                "Senegal",
			ISO3166_1_numeric:   686,
			ISO3166_2:           "SN",
			ISO3166_3:           "SEN",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"RS": {
			Name:                "Serbia",
			ISO3166_1_numeric:   688,
			ISO3166_2:           "RS",
			ISO3166_3:           "SRB",
			DefaultCurrency:     "RSD",
			DefaultLanguage:     "sr",
			EuropeanUnionMember: false,
		},
		"SC": {
			Name:                "Seychelles",
			ISO3166_1_numeric:   690,
			ISO3166_2:           "SC",
			ISO3166_3:           "SYC",
			DefaultCurrency:     "SCR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"SL": {
			Name:                "Sierra Leone",
			ISO3166_1_numeric:   694,
			ISO3166_2:           "SL",
			ISO3166_3:           "SLE",
			DefaultCurrency:     "SLL",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"SG": {
			Name:                "Singapore",
			ISO3166_1_numeric:   702,
			ISO3166_2:           "SG",
			ISO3166_3:           "SGP",
			DefaultCurrency:     "SGD",
			DefaultLanguage:     "zh",
			EuropeanUnionMember: false,
		},
		"SX": {
			Name:                "Sint Maarten",
			ISO3166_1_numeric:   534,
			ISO3166_2:           "SX",
			ISO3166_3:           "SXM",
			DefaultCurrency:     "ANG",
			DefaultLanguage:     "nl",
			EuropeanUnionMember: false,
		},
		"SK": {
			Name:                "Slovakia",
			ISO3166_1_numeric:   703,
			ISO3166_2:           "SK",
			ISO3166_3:           "SVK",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "cs",
			EuropeanUnionMember: true,
		},
		"SI": {
			Name:                "Slovenia",
			ISO3166_1_numeric:   705,
			ISO3166_2:           "SI",
			ISO3166_3:           "SVN",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "it",
			EuropeanUnionMember: true,
		},
		"SB": {
			Name:                "Solomon Islands",
			ISO3166_1_numeric:   90,
			ISO3166_2:           "SB",
			ISO3166_3:           "SLB",
			DefaultCurrency:     "SBD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"SO": {
			Name:                "Somalia",
			ISO3166_1_numeric:   706,
			ISO3166_2:           "SO",
			ISO3166_3:           "SOM",
			DefaultCurrency:     "SOS",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"ZA": {
			Name:                "South Africa",
			ISO3166_1_numeric:   710,
			ISO3166_2:           "ZA",
			ISO3166_3:           "ZAF",
			DefaultCurrency:     "ZAR",
			DefaultLanguage:     "af",
			EuropeanUnionMember: false,
		},
		"GS": {
			Name:                "South Georgia and the South Sandwich Islands",
			ISO3166_1_numeric:   239,
			ISO3166_2:           "GS",
			ISO3166_3:           "SGS",
			DefaultCurrency:     "GBP",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"SS": {
			Name:                "South Sudan",
			ISO3166_1_numeric:   728,
			ISO3166_2:           "SS",
			ISO3166_3:           "SSD",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"ES": {
			Name:                "Spain",
			ISO3166_1_numeric:   724,
			ISO3166_2:           "ES",
			ISO3166_3:           "ESP",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "es",
			EuropeanUnionMember: true,
		},
		"LK": {
			Name:                "Sri Lanka",
			ISO3166_1_numeric:   144,
			ISO3166_2:           "LK",
			ISO3166_3:           "LKA",
			DefaultCurrency:     "LKR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"PS": {
			Name:                "State of Palestine",
			ISO3166_1_numeric:   275,
			ISO3166_2:           "PS",
			ISO3166_3:           "PSE",
			DefaultCurrency:     "JOD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"SD": {
			Name:                "Sudan",
			ISO3166_1_numeric:   729,
			ISO3166_2:           "SD",
			ISO3166_3:           "SDN",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"SR": {
			Name:                "Suriname",
			ISO3166_1_numeric:   740,
			ISO3166_2:           "SR",
			ISO3166_3:           "SUR",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "nl",
			EuropeanUnionMember: false,
		},
		"SJ": {
			Name:                "Svalbard and Jan Mayen Islands",
			ISO3166_1_numeric:   744,
			ISO3166_2:           "SJ",
			ISO3166_3:           "SJM",
			DefaultCurrency:     "NOK",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"SE": {
			Name:                "Sweden",
			ISO3166_1_numeric:   752,
			ISO3166_2:           "SE",
			ISO3166_3:           "SWE",
			DefaultCurrency:     "SEK",
			DefaultLanguage:     "sv",
			EuropeanUnionMember: true,
		},
		"CH": {
			Name:                "Switzerland",
			ISO3166_1_numeric:   756,
			ISO3166_2:           "CH",
			ISO3166_3:           "CHE",
			DefaultCurrency:     "CHF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"SY": {
			Name:                "Syrian Arab Republic",
			ISO3166_1_numeric:   760,
			ISO3166_2:           "SY",
			ISO3166_3:           "SYR",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"TW": {
			Name:                "Taiwan",
			ISO3166_1_numeric:   158,
			ISO3166_2:           "TW",
			ISO3166_3:           "TWN",
			DefaultCurrency:     "TWD",
			DefaultLanguage:     "zh",
			EuropeanUnionMember: false,
		},
		"TJ": {
			Name:                "Tajikistan",
			ISO3166_1_numeric:   762,
			ISO3166_2:           "TJ",
			ISO3166_3:           "TJK",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "fa",
			EuropeanUnionMember: false,
		},
		"TH": {
			Name:                "Thailand",
			ISO3166_1_numeric:   764,
			ISO3166_2:           "TH",
			ISO3166_3:           "THA",
			DefaultCurrency:     "THB",
			DefaultLanguage:     "th",
			EuropeanUnionMember: false,
		},
		"MK": {
			Name:                "The former Yugoslav Republic of Macedonia",
			ISO3166_1_numeric:   807,
			ISO3166_2:           "MK",
			ISO3166_3:           "MKD",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "mk",
			EuropeanUnionMember: false,
		},
		"TL": {
			Name:                "Timor-Leste",
			ISO3166_1_numeric:   626,
			ISO3166_2:           "TL",
			ISO3166_3:           "TLS",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "pt",
			EuropeanUnionMember: false,
		},
		"TG": {
			Name:                "Togo",
			ISO3166_1_numeric:   768,
			ISO3166_2:           "TG",
			ISO3166_3:           "TGO",
			DefaultCurrency:     "XOF",
			DefaultLanguage:     "ee",
			EuropeanUnionMember: false,
		},
		"TK": {
			Name:                "Tokelau",
			ISO3166_1_numeric:   772,
			ISO3166_2:           "TK",
			ISO3166_3:           "TKL",
			DefaultCurrency:     "NZD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"TO": {
			Name:                "Tonga",
			ISO3166_1_numeric:   776,
			ISO3166_2:           "TO",
			ISO3166_3:           "TON",
			DefaultCurrency:     "TOP",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"TT": {
			Name:                "Trinidad and Tobago",
			ISO3166_1_numeric:   780,
			ISO3166_2:           "TT",
			ISO3166_3:           "TTO",
			DefaultCurrency:     "TTD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"TN": {
			Name:                "Tunisia",
			ISO3166_1_numeric:   788,
			ISO3166_2:           "TN",
			ISO3166_3:           "TUN",
			DefaultCurrency:     "TND",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"TR": {
			Name:                "Turkey",
			ISO3166_1_numeric:   792,
			ISO3166_2:           "TR",
			ISO3166_3:           "TUR",
			DefaultCurrency:     "TRY",
			DefaultLanguage:     "tr",
			EuropeanUnionMember: false,
		},
		"TM": {
			Name:                "Turkmenistan",
			ISO3166_1_numeric:   795,
			ISO3166_2:           "TM",
			ISO3166_3:           "TKM",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "tk",
			EuropeanUnionMember: false,
		},
		"TC": {
			Name:                "Turks and Caicos Islands",
			ISO3166_1_numeric:   796,
			ISO3166_2:           "TC",
			ISO3166_3:           "TCA",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"TV": {
			Name:                "Tuvalu",
			ISO3166_1_numeric:   798,
			ISO3166_2:           "TV",
			ISO3166_3:           "TUV",
			DefaultCurrency:     "AUD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"UG": {
			Name:                "Uganda",
			ISO3166_1_numeric:   800,
			ISO3166_2:           "UG",
			ISO3166_3:           "UGA",
			DefaultCurrency:     "UGX",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"UA": {
			Name:                "Ukraine",
			ISO3166_1_numeric:   804,
			ISO3166_2:           "UA",
			ISO3166_3:           "UKR",
			DefaultCurrency:     "UAH",
			DefaultLanguage:     "uk",
			EuropeanUnionMember: false,
		},
		"AE": {
			Name:                "United Arab Emirates",
			ISO3166_1_numeric:   784,
			ISO3166_2:           "AE",
			ISO3166_3:           "ARE",
			DefaultCurrency:     "AED",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"GB": {
			Name:                "United Kingdom",
			ISO3166_1_numeric:   826,
			ISO3166_2:           "GB",
			ISO3166_3:           "GBR",
			DefaultCurrency:     "GBP",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"TZ": {
			Name:                "United Republic of Tanzania",
			ISO3166_1_numeric:   834,
			ISO3166_2:           "TZ",
			ISO3166_3:           "TZA",
			DefaultCurrency:     "TZS",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"UM": {
			Name:                "United States Minor Outlying Islands",
			ISO3166_1_numeric:   581,
			ISO3166_2:           "UM",
			ISO3166_3:           "UMI",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"US": {
			Name:                "United States of America",
			ISO3166_1_numeric:   840,
			ISO3166_2:           "US",
			ISO3166_3:           "USA",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"VI": {
			Name:                "United States Virgin Islands",
			ISO3166_1_numeric:   850,
			ISO3166_2:           "VI",
			ISO3166_3:           "VIR",
			DefaultCurrency:     "USD",
			DefaultLanguage:     "",
			EuropeanUnionMember: false,
		},
		"UY": {
			Name:                "Uruguay",
			ISO3166_1_numeric:   858,
			ISO3166_2:           "UY",
			ISO3166_3:           "URY",
			DefaultCurrency:     "UYU",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"UZ": {
			Name:                "Uzbekistan",
			ISO3166_1_numeric:   860,
			ISO3166_2:           "UZ",
			ISO3166_3:           "UZB",
			DefaultCurrency:     "UZS",
			DefaultLanguage:     "uz",
			EuropeanUnionMember: false,
		},
		"VU": {
			Name:                "Vanuatu",
			ISO3166_1_numeric:   548,
			ISO3166_2:           "VU",
			ISO3166_3:           "VUT",
			DefaultCurrency:     "VUV",
			DefaultLanguage:     "bi",
			EuropeanUnionMember: false,
		},
		"VE": {
			Name:                "Venezuela",
			ISO3166_1_numeric:   862,
			ISO3166_2:           "VE",
			ISO3166_3:           "VEN",
			DefaultCurrency:     "VEF",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"VN": {
			Name:                "Vietnam",
			ISO3166_1_numeric:   704,
			ISO3166_2:           "VN",
			ISO3166_3:           "VNM",
			DefaultCurrency:     "VND",
			DefaultLanguage:     "vi",
			EuropeanUnionMember: false,
		},
		"WF": {
			Name:                "Wallis and Futuna Islands",
			ISO3166_1_numeric:   876,
			ISO3166_2:           "WF",
			ISO3166_3:           "WLF",
			DefaultCurrency:     "XPF",
			DefaultLanguage:     "fr",
			EuropeanUnionMember: false,
		},
		"EH": {
			Name:                "Western Sahara",
			ISO3166_1_numeric:   732,
			ISO3166_2:           "EH",
			ISO3166_3:           "ESH",
			DefaultCurrency:     "MAD",
			DefaultLanguage:     "es",
			EuropeanUnionMember: false,
		},
		"YE": {
			Name:                "Yemen",
			ISO3166_1_numeric:   887,
			ISO3166_2:           "YE",
			ISO3166_3:           "YEM",
			DefaultCurrency:     "YER",
			DefaultLanguage:     "ar",
			EuropeanUnionMember: false,
		},
		"ZM": {
			Name:                "Zambia",
			ISO3166_1_numeric:   894,
			ISO3166_2:           "ZM",
			ISO3166_3:           "ZMB",
			DefaultCurrency:     "ZMW",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"ZW": {
			Name:                "Zimbabwe",
			ISO3166_1_numeric:   716,
			ISO3166_2:           "ZW",
			ISO3166_3:           "ZWE",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "en",
			EuropeanUnionMember: false,
		},
		"AX": {
			Name:                "Åland Islands",
			ISO3166_1_numeric:   248,
			ISO3166_2:           "AX",
			ISO3166_3:           "ALA",
			DefaultCurrency:     "EUR",
			DefaultLanguage:     "sv",
			EuropeanUnionMember: false,
		},
	}

	for _, c := range byISO2 {
		byISO3[c.ISO3166_3] = c
		byISO1Numeric[c.ISO3166_1_numeric] = c
	}
}

func ByAlpha2(a2 string) (Info, bool) {
	code := byISO2[a2]

	return code, code.ISO3166_2 != ""
}

func ByAlpha3(a3 string) (Info, bool) {
	code := byISO3[a3]

	return code, code.ISO3166_3 != ""
}

func ByNumeric(num int) (Info, bool) {
	code := byISO1Numeric[num]
	return code, code.ISO3166_1_numeric != 0
}

func All() []Info {
	all := make([]Info, 0, len(byISO2))
	for _, c := range byISO2 {
		all = append(all, c)
	}
	return all
}
