package country

import (
	"strings"

	"golang.org/x/text/language"
)

var languagesByCountry = map[string]([]language.Tag){
	"AD": []language.Tag{language.Catalan},
	"AE": []language.Tag{language.Arabic, language.English},
	"AF": []language.Tag{language.Persian},
	"AG": []language.Tag{language.English},
	"AI": []language.Tag{language.English},
	"AL": []language.Tag{language.Albanian},
	"AM": []language.Tag{language.Armenian},
	"AO": []language.Tag{language.Portuguese},
	"AQ": []language.Tag{language.English},
	"AR": []language.Tag{language.Spanish},
	"AS": []language.Tag{language.English},
	"AT": []language.Tag{language.German},
	"AU": []language.Tag{language.English},
	"AW": []language.Tag{language.Dutch},
	"AX": []language.Tag{language.Finnish, language.Swedish},
	"AZ": []language.Tag{language.Azerbaijani},
	"BA": []language.Tag{language.Serbian, language.Croatian},
	"BB": []language.Tag{language.English},
	"BD": []language.Tag{language.Bengali},
	"BE": []language.Tag{language.French, language.Dutch, language.German},
	"BF": []language.Tag{language.French},
	"BG": []language.Tag{language.Bulgarian},
	"BH": []language.Tag{language.Arabic, language.English},
	"BI": []language.Tag{language.English},
	"BJ": []language.Tag{language.French},
	"BL": []language.Tag{language.French},
	"BM": []language.Tag{language.English},
	"BN": []language.Tag{language.English, language.Malay},
	"BO": []language.Tag{language.Spanish},
	"BQ": []language.Tag{language.Dutch, language.English},
	"BR": []language.Tag{language.Portuguese, language.BrazilianPortuguese},
	"BS": []language.Tag{language.English},
	"BV": []language.Tag{language.Norwegian},
	"BW": []language.Tag{language.English},
	"BY": []language.Tag{language.Russian},
	"BZ": []language.Tag{language.English, language.Spanish},
	"CA": []language.Tag{language.English, language.French, language.CanadianFrench},
	"CC": []language.Tag{language.English},
	"CD": []language.Tag{language.French},
	"CF": []language.Tag{language.French},
	"CG": []language.Tag{language.French},
	"CH": []language.Tag{language.German, language.French, language.Italian},
	"CI": []language.Tag{language.French},
	"CK": []language.Tag{language.English},
	"CL": []language.Tag{language.Spanish},
	"CM": []language.Tag{language.English},
	"CN": []language.Tag{language.Chinese},
	"CO": []language.Tag{language.Spanish},
	"CR": []language.Tag{language.Spanish},
	"CU": []language.Tag{language.Spanish},
	"CV": []language.Tag{language.Portuguese},
	"CW": []language.Tag{language.English, language.Dutch},
	"CX": []language.Tag{language.English},
	"CY": []language.Tag{language.Greek},
	"CZ": []language.Tag{language.Czech},
	"DE": []language.Tag{language.German},
	"DJ": []language.Tag{language.Arabic, language.French},
	"DK": []language.Tag{language.Danish},
	"DM": []language.Tag{language.English},
	"DO": []language.Tag{language.Spanish},
	"DZ": []language.Tag{language.Arabic, language.French},
	"EC": []language.Tag{language.Spanish},
	"EE": []language.Tag{language.Estonian},
	"EG": []language.Tag{language.Arabic},
	"EH": []language.Tag{language.Arabic},
	"ER": []language.Tag{language.Arabic, language.Italian},
	"ES": []language.Tag{language.Spanish, language.Catalan},
	"ET": []language.Tag{language.Amharic},
	"FI": []language.Tag{language.Finnish, language.Swedish},
	"FJ": []language.Tag{language.English},
	"FK": []language.Tag{language.English},
	"FM": []language.Tag{language.English},
	"FO": []language.Tag{language.Danish},
	"FR": []language.Tag{language.French},
	"GA": []language.Tag{language.French},
	"GB": []language.Tag{language.English, language.BritishEnglish},
	"GD": []language.Tag{language.English},
	"GE": []language.Tag{language.Georgian},
	"GG": []language.Tag{language.English},
	"GF": []language.Tag{language.French},
	"GH": []language.Tag{language.English},
	"GI": []language.Tag{language.English},
	"GL": []language.Tag{language.Danish},
	"GM": []language.Tag{language.English},
	"GN": []language.Tag{language.French},
	"GP": []language.Tag{language.French},
	"GQ": []language.Tag{language.Spanish, language.French, language.Portuguese},
	"GR": []language.Tag{language.Greek},
	"GS": []language.Tag{language.English},
	"GT": []language.Tag{language.Spanish},
	"GU": []language.Tag{language.English},
	"GW": []language.Tag{language.Portuguese},
	"GY": []language.Tag{language.English},
	"HK": []language.Tag{language.English, language.Chinese},
	"HM": []language.Tag{language.English},
	"HN": []language.Tag{language.Spanish},
	"HR": []language.Tag{language.Croatian},
	"HT": []language.Tag{language.French},
	"HU": []language.Tag{language.Hungarian},
	"ID": []language.Tag{language.Indonesian},
	"IE": []language.Tag{language.English},
	"IL": []language.Tag{language.Arabic, language.Greek},
	"IM": []language.Tag{language.English},
	"IN": []language.Tag{language.English},
	"IO": []language.Tag{language.English},
	"IQ": []language.Tag{language.Arabic},
	"IR": []language.Tag{language.Persian},
	"IS": []language.Tag{language.Icelandic},
	"IT": []language.Tag{language.Italian},
	"JE": []language.Tag{language.English},
	"JM": []language.Tag{language.English},
	"JO": []language.Tag{language.Arabic},
	"JP": []language.Tag{language.Japanese},
	"KE": []language.Tag{language.English},
	"KG": []language.Tag{language.Kirghiz, language.Russian},
	"KH": []language.Tag{language.Khmer},
	"KI": []language.Tag{language.English},
	"KM": []language.Tag{language.Arabic, language.French},
	"KN": []language.Tag{language.English},
	"KP": []language.Tag{language.Korean},
	"KR": []language.Tag{language.Korean},
	"KW": []language.Tag{language.Arabic},
	"KY": []language.Tag{language.English},
	"KZ": []language.Tag{language.Kazakh, language.Russian},
	"LA": []language.Tag{language.Lao},
	"LB": []language.Tag{language.Arabic},
	"LC": []language.Tag{language.English},
	"LI": []language.Tag{language.German},
	"LK": []language.Tag{language.English, language.Sinhala, language.Tamil},
	"LR": []language.Tag{language.English},
	"LS": []language.Tag{language.English},
	"LT": []language.Tag{language.Lithuanian},
	"LU": []language.Tag{language.German, language.French},
	"LV": []language.Tag{language.Lithuanian},
	"LY": []language.Tag{language.Arabic},
	"MA": []language.Tag{language.Arabic, language.French},
	"MC": []language.Tag{language.French},
	"MD": []language.Tag{language.Romanian},
	"ME": []language.Tag{language.Serbian},
	"MF": []language.Tag{language.French},
	"MG": []language.Tag{language.French},
	"MH": []language.Tag{language.English},
	"MK": []language.Tag{language.Macedonian, language.Albanian},
	"ML": []language.Tag{language.French},
	"MM": []language.Tag{language.Burmese},
	"MN": []language.Tag{language.Mongolian},
	"MO": []language.Tag{language.Portuguese, language.Chinese},
	"MP": []language.Tag{language.English},
	"MQ": []language.Tag{language.French},
	"MR": []language.Tag{language.Arabic, language.French},
	"MS": []language.Tag{language.English},
	"MT": []language.Tag{language.English},
	"MU": []language.Tag{language.English, language.French},
	"MW": []language.Tag{language.English},
	"MX": []language.Tag{language.Spanish},
	"MY": []language.Tag{language.Malay},
	"MZ": []language.Tag{language.Portuguese},
	"NA": []language.Tag{language.English},
	"NC": []language.Tag{language.French},
	"NE": []language.Tag{language.French},
	"NF": []language.Tag{language.English},
	"NG": []language.Tag{language.Spanish},
	"NI": []language.Tag{language.Spanish},
	"NL": []language.Tag{language.Dutch},
	"NO": []language.Tag{language.Norwegian},
	"NP": []language.Tag{language.English},
	"NR": []language.Tag{language.English},
	"NU": []language.Tag{language.English},
	"NZ": []language.Tag{language.English},
	"OM": []language.Tag{language.Arabic, language.English},
	"PA": []language.Tag{language.Spanish},
	"PE": []language.Tag{language.Spanish},
	"PF": []language.Tag{language.French},
	"PG": []language.Tag{language.English},
	"PH": []language.Tag{language.English},
	"PK": []language.Tag{language.English},
	"PL": []language.Tag{language.Polish},
	"PM": []language.Tag{language.French},
	"PN": []language.Tag{language.English},
	"PR": []language.Tag{language.English, language.Spanish},
	"PS": []language.Tag{language.Arabic},
	"PT": []language.Tag{language.Portuguese},
	"PW": []language.Tag{language.English},
	"PY": []language.Tag{language.Spanish},
	"QA": []language.Tag{language.Arabic, language.English},
	"RE": []language.Tag{language.French},
	"RO": []language.Tag{language.Romanian},
	"RS": []language.Tag{language.Serbian},
	"RU": []language.Tag{language.Russian},
	"RW": []language.Tag{language.English, language.French, language.Swahili},
	"SA": []language.Tag{language.Arabic},
	"SB": []language.Tag{language.English},
	"SC": []language.Tag{language.English, language.French},
	"SD": []language.Tag{language.Arabic, language.English},
	"SE": []language.Tag{language.Swedish},
	"SG": []language.Tag{language.English},
	"SH": []language.Tag{language.English},
	"SI": []language.Tag{language.Slovenian},
	"SJ": []language.Tag{language.Norwegian},
	"SK": []language.Tag{language.Slovak},
	"SL": []language.Tag{language.English},
	"SM": []language.Tag{language.Italian},
	"SN": []language.Tag{language.French},
	"SO": []language.Tag{language.Arabic},
	"SR": []language.Tag{language.Dutch},
	"SS": []language.Tag{language.English},
	"ST": []language.Tag{language.Portuguese},
	"SV": []language.Tag{language.Spanish},
	"SX": []language.Tag{language.English, language.Dutch},
	"SY": []language.Tag{language.Arabic},
	"SZ": []language.Tag{language.English},
	"TC": []language.Tag{language.English},
	"TD": []language.Tag{language.French},
	"TF": []language.Tag{language.French},
	"TG": []language.Tag{language.French},
	"TH": []language.Tag{language.Thai},
	"TJ": []language.Tag{language.Russian},
	"TK": []language.Tag{language.English},
	"TL": []language.Tag{language.English, language.Indonesian, language.Portuguese},
	"TN": []language.Tag{language.Arabic, language.French},
	"TM": []language.Tag{language.Russian},
	"TO": []language.Tag{language.English},
	"TR": []language.Tag{language.Turkish},
	"TT": []language.Tag{language.English},
	"TV": []language.Tag{language.English},
	"TW": []language.Tag{language.Chinese},
	"TZ": []language.Tag{language.English, language.Swahili},
	"UA": []language.Tag{language.Ukrainian},
	"UG": []language.Tag{language.English, language.Swahili},
	"UM": []language.Tag{language.English},
	"US": []language.Tag{language.English, language.AmericanEnglish},
	"UY": []language.Tag{language.Spanish},
	"UZ": []language.Tag{language.Uzbek},
	"VA": []language.Tag{language.Italian},
	"VC": []language.Tag{language.English},
	"VE": []language.Tag{language.Spanish},
	"VG": []language.Tag{language.English},
	"VI": []language.Tag{language.English},
	"VN": []language.Tag{language.Vietnamese},
	"VU": []language.Tag{language.English},
	"WF": []language.Tag{language.French},
	"WS": []language.Tag{language.English},
	"YE": []language.Tag{language.Arabic},
	"YT": []language.Tag{language.French},
	"ZA": []language.Tag{language.English},
	"ZM": []language.Tag{language.English},
	"ZW": []language.Tag{language.English},
}

// Languages for a country.
func Languages(country string) []language.Tag {
	return languagesByCountry[strings.ToUpper(country)]
}
